### ISSUE TITLE
JSON_PRETTY_PRINT as default?

### ISSUE THREAD

**Issue by snapshotpl** [zendframework/zend-problem-details#4]
Should we serve problem details in json with JSON_PRETTY_PRINT flag? For debugging maybe it's useful, but in normal working it's add additional data to transfer.

My proposition is to enable this flag in debug mode or remove it in default settings.

**Comment by snapshotpl** [comment]
@weierophinney ping

**Comment by weierophinney** [comment]
@snapshotpl send a PR, please.

**Comment by samsonasik** [comment]
@snapshotpl @weierophinney I've created PR #34 for it.

**Comment by samsonasik** [comment]
@snapshotpl can be closed in favor of #34

**Comment by snapshotpl** [comment]
@samsonasik thanks! Looks perfect for me :+1:
