### ISSUE TITLE
[documentation] Typos on the online documentation

### ISSUE THREAD

**Issue by guillaumemaka** [zendframework/zend-problem-details#43]
- [X] I was not able to find an [open](https://github.com/zendframework/zend-expressive-hal/issues?q=is%3Aopen) or [closed](https://github.com/zendframework/zend-expressive-hal/issues?q=is%3Aclosed) issue matching what I'm seeing.
 - [X] This is not a question. (Questions should be asked on [slack](https://zendframework.slack.com/) ([Signup for Slack here](https://zendframework-slack.herokuapp.com/)) or our [forums](https://discourse.zendframework.com/).)

Provide a narrative description of what you are trying to accomplish.

There are typos on the documentation page https://docs.zendframework.com/zend-problem-details/

- Issue and source code links
- composer installation package name

**Comment by froschdesign** [comment]
@guillaumemaka 
Good catch!

**Comment by kachar** [comment]
Possible regression since https://github.com/zendframework/zf3-web/pull/107

**Comment by Repkit** [comment]
I've created a PR for composer installation package name

**Comment by froschdesign** [comment]
The MkDocs configurations needs an update:
https://github.com/zendframework/zend-problem-details/blob/master/mkdocs.yml#L12

The `site_name` must be:

```yaml
site_name: zend-problem-details
```
