### ISSUE TITLE
Line return and cleaning function. Bug ?

### ISSUE THREAD

**Issue by ncou** [zendframework/zend-problem-details#45]
Hi,

Very nice piece of code. I am using a part of your code, and i think i found a bug during one of my tests.

I tried to add a line return (chr(10) => \n) in the array key name to check if the function "cleanKeysForXml()" work correctly and i got an error.

I think the regex is using at the end the "." char for "Matches any character" but it doesn't take in consideration the lines terminators. So the Chr(10) is not replaced by an underscore in this cleaning function.

if you remove any line return character before calling the regex it seems to me it's more bulletproof.

Is this a bug or am i missing something ?

**Comment by Ocramius** [comment]
@ncou could you please add an example of code triggering the issue?

**Comment by ncou** [comment]
Sure.

You can modify the phpunit test [testCreateResponseRemovesInvalidCharactersFromXmlKeys](https://github.com/zendframework/zend-problem-details/blob/master/test/ProblemDetailsResponseFactoryTest.php#L147) like this (i have added 2 examples at the end of the $additional array using \n and chr(10).) :

```php
$additional = [
            'foo' => [
                'A#-' => 'foo',
                '-A-' => 'foo',
                '#B-' => 'foo',
                "foo\nbar" => 'foo',
                'bar' . chr(10) . 'foo' => 'foo',
            ],
        ];

        if (stripos($expectedType, 'xml')) {
            $expectedKeyNames = [
                'A_-',
                '_A-',
                '_B-',
                'foo_bar',
                'bar_foo',
            ];
        } else {
            $expectedKeyNames = array_keys($additional['foo']);
        }
```
and you will get the error.

You can also test directly the cleanXml method like this in a basic index.php file : 

```php
use Zend\ProblemDetails\ProblemDetailsResponseFactory;

require __DIR__ . '/vendor/autoload.php';

$method = new ReflectionMethod(ProblemDetailsResponseFactory::class, 'cleanKeysForXml');
$method->setAccessible(true);
$xmlBug = new ProblemDetailsResponseFactory(function(){});

$xmlValues = ['foo'.chr(10).'bar' => 'foo'];

$res = $method->invoke($xmlBug, $xmlValues);

die(var_dump($res));
```

The problem is the regex doesn't take in count the line return so it's not filtered and the Dom document object crash with a "DOMException: Invalid Character Error" exception.

For the moment i have used a fix `$key = str_replace(chr(10), '_', $key);` just before the regex. 
I am not really an expert in the regex so i doesn't made any modifications, but there is possibly a cleaner solution than my fix.

**Comment by Ocramius** [comment]
Would you be able to put the above example in the context of https://github.com/zendframework/zend-problem-details/blob/6951508290d6259b752dbb185e50b3c729937a98/test/ProblemDetailsResponseFactoryTest.php? Assuming (big assumption!) that the fix is trivial, a pull request with just the failing test case is 90%+ of the work already done :+1:

**Comment by ncou** [comment]
My english is not very good, so to be sure, you want me to do a pull request in the "develop" branch with my failing testcase ? is that right ?

**Comment by Ocramius** [comment]
Since this is a `bug`, create a new branch off `master`, then send a pull request against `master` with your test case committed :+1:

**Comment by ncou** [comment]
Ok, I made the pullrequest and used the same pattern as you (or the main dev in this repo) for the test (using 'A_-' result instead of 'foo_bar').

Tell me if it's all good, or if i need to do some changes.

**Comment by Ocramius** [comment]
@ncou looking good, thanks!

Nitpicks on it can be discussed later on, but for now either somebody adds a fix to it, or you do it (by just pushing to the same branch)

**Comment by ncou** [comment]
I will wait a few days to see if someone have a better solution, else i will push my fix using str_replace and not changing the regex pattern.

**Comment by michalbundyra** [comment]
@ncou I was looking on it couple days ago, and for me `str_replace` is the best solution. I've tried modify the regexp but without success. `str_replace` should be clear enough.

The only thing I would check how it works for other white characters - like `\r`, `\t`, ...

**Comment by ncou** [comment]
looking at the site https://regex101.com/ the dot char (used at the end of the zend regex) is indicated as "matches any character (except for line terminators) => line terminator is \n" so i think only \n could be missed by the regex.

To be sure I made a local test with \r and \t and there are correctly transformed as "_".
